### ISSUE TITLE
Remove case-sensitive from input

### ISSUE THREAD

**Issue by christopherfrige** [nikhilpark/ApexLegendsInfo#2]
When you put any upper-case characters the script returns "thats not a legend!!"

Example:
• Doesn't work:
<img src="https://i.imgur.com/xiRZPd4.png"/>

• Works:
<img src="https://i.imgur.com/JmEoEgH.png"/>

**Comment by nikhilpark** [comment]
![in](https://user-images.githubusercontent.com/69470795/125235592-545fc600-e300-11eb-99ca-7fe15567a7c3.PNG)

Fixed by changing input received from user to lowercase by default
